---
services:
  nginx-proxy:
    image: "ghcr.io/rkoval/infrastructure:nginx-latest"
    build:
      context: ./nginx
      x-bake:
        platforms:
          - linux/amd64
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    volumes:
      - /opt/nginx/certs:/etc/nginx/certs
      - letsencrypt-vhost:/etc/nginx/vhost.d-letsencrypt
      - letsencrypt-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /opt/nginx/certs:/etc/nginx/certs
      - letsencrypt-vhost:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # environment:
      # uncomment to test with staging certs that have no rate limits
      # - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory

  order-me-pizza:
    image: "ghcr.io/rkoval/order-me-pizza:latest"
    restart: always
    build:
      context: ./order-me-pizza
      x-bake:
        platforms:
          - linux/amd64
    environment:
      - VIRTUAL_HOST=ryankoval.pizza,www.ryankoval.pizza,ryankoval.pizza.local
      - LETSENCRYPT_HOST=ryankoval.pizza,www.ryankoval.pizza
      - LETSENCRYPT_EMAIL=ryan@ryankoval.com
      - NODE_CONFIG={}
      - NODE_ENV=production

  ryankoval.com:
    image: "ghcr.io/rkoval/ryankoval.com:latest"
    restart: always
    build:
      context: ./ryankoval.com
      x-bake:
        platforms:
          - linux/amd64
    environment:
      - VIRTUAL_HOST=ryankoval.com,www.ryankoval.com,resume.ryankoval.com,ryankoval.local,resume.ryankoval.local,avatar.ryankoval.com,avatar.ryankoval.local,bookmarks.ryankoval.com,dotfiles.ryankoval.com,github.ryankoval.com,linkedin.ryankoval.com,twitter.ryankoval.com,portfolio.ryankoval.com
      - LETSENCRYPT_HOST=ryankoval.com,www.ryankoval.com,resume.ryankoval.com,avatar.ryankoval.com,bookmarks.ryankoval.com,dotfiles.ryankoval.com,github.ryankoval.com,linkedin.ryankoval.com,twitter.ryankoval.com,portfolio.ryankoval.com
      - LETSENCRYPT_EMAIL=ryan@ryankoval.com
      - NODE_ENV=production

  ghost:
    image: ghost:5.55.2-alpine
    restart: always
    environment:
      - VIRTUAL_HOST=blog.ryankoval.com,blog.ryankoval.local
      - LETSENCRYPT_HOST=blog.ryankoval.com
      - LETSENCRYPT_EMAIL=ryan@ryankoval.com
      - NODE_ENV=production
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=root
      - database__connection__password=example
      - database__connection__database=ghost
      - url=https://blog.ryankoval.com
    volumes:
      - ./ghost-data:/var/lib/ghost/content

  ghost-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example

  wedding-website:
    image: "ghcr.io/rkoval/wedding-website:latest"
    restart: always
    build:
      context: ./wedding-website
      x-bake:
        platforms:
          - linux/amd64
    environment:
      - VIRTUAL_HOST=caterina.and.ryankoval.com,caterina.and.ryankoval.local
      - LETSENCRYPT_HOST=caterina.and.ryankoval.com
      - LETSENCRYPT_EMAIL=ryan@ryankoval.com
      - NODE_ENV=production

  rooooney:
    image: "ghcr.io/rkoval/rooooney:latest"
    restart: always
    build:
      context: ./rooooney
      x-bake:
        platforms:
          - linux/amd64
    environment:
      - VIRTUAL_HOST=rooooney.ryankoval.com,rooooney.local
      - LETSENCRYPT_HOST=rooooney.ryankoval.com
      - LETSENCRYPT_EMAIL=ryan@ryankoval.com
      - NODE_ENV=production

volumes:
  letsencrypt-html:
  letsencrypt-vhost:
