name: main

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  ENVIRONMENT: CI
  TERM: xterm-256color

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true # private submodules fail to clone
        with:
          submodules: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker compose build ryankoval.com
      - run: docker compose push ryankoval.com
      - if: always()
        run: docker logout